### PR TITLE
fix(operations): fail fast the current batch to respect the operations limit

### LINKED ISSUE #466: operations-per-run appears to be ignored
I set this to 1:

https://github.com/grpc/grpc-go/runs/2667832758?check_suite_focus=true#step:2:9

Yet 2 issues were marked as stale during this run:

https://github.com/grpc/grpc-go/runs/2667832758?check_suite_focus=true#step:2:117
https://github.com/grpc/grpc-go/runs/2667832758?check_suite_focus=true#step:2:194

### PR DESCRIPTION
**Pull request by C0ZEN**
## Changes

- [x] fix a bad stats related to the consumed operations
- [x] display the stats when the operations per run stopped the workflow
- [x] fail fast the current batch to respect the operations limit, fixes #466
- [x] disable the dry-run for the test by default

### CODE REVIEW

File: src/classes/issues-processor.ts [hunk 1]
```diff
@@ -121,6 +121,11 @@ export class IssuesProcessor {
     }
 
     for (const issue of issues.values()) {
+      // Stop the processing if no more operations remains
+      if (!this.operations.hasRemainingOperations()) {
+        break;
```
Comment (luketomlinson) [inline src/classes/issues-processor.ts:126]: maybe a log here so the user knows why issues weren't processed?

Comment (C0ZEN) [reply src/classes/issues-processor.ts:126]: No need, this code will be executed after the break
https://github.com/C0ZEN/stale/blob/2f93a2a49f4c195ae653bb1d88195f1ada50c8f7/src/classes/issues-processor.ts#L407

Comment (luketomlinson) [reply src/classes/issues-processor.ts:126]: ah I see it now. It's just a big loop 😂

**Review by luketomlinson — APPROVED** [review]

File: src/classes/issues-processor.ts (hunk 1 above)
Comment (C0ZEN) [reply src/classes/issues-processor.ts:126]: I am not fond of this because it's not obvious but yeah, one day it would be nice to make the code cleaner!
